name: Build Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clean up disk space before build
        run: |
          echo "Before cleanup:"
          df -h
          sudo docker system prune -af || true
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc || true
          echo "After cleanup:"
          df -h

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check disk space before build
        run: df -h

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: sunchainltd/lc-fine-tune:1.1
          no-cache: true

      - name: Check disk space after build
        run: df -h
